version: '3.3'

services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.prod
    expose:
      - 3000
    networks:
      - internal
    restart: always

  reverse_proxy:
    build: reverse_proxy
    ports:
      - "3000:3000"
    depends_on:
      - frontend
      - backend
    networks:
      - internal
    restart: always

  backend:
    build:
      context: backend
      dockerfile: Dockerfile.prod
    expose:
      - 3000
    networks:
      - internal
    restart: always

  database:
    image: "postgres:alpine3.15"
    expose:
      - 5432
    volumes:
      - "database:/var/lib/postgresql/data"
    networks:
      - internal
    restart: always

volumes:
  database:


networks:
  internal:
