version: '3.3'

services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    volumes:
      - "./frontend/app:/app"
    expose:
      - 3000
    networks:
      - internal

  reverse_proxy:
    build: reverse_proxy
    ports:
      - "3000:3000"
    networks:
      - internal
    depends_on:
      - frontend
      - backend

  backend:
    build:
      context: backend
      dockerfile: Dockerfile.dev
    volumes:
      - "./backend/app:/app"
    expose:
      - 3000
    networks:
      - internal

  database:
    image: "postgres:alpine3.15"
    expose:
      - 5432
    volumes:
      - "database:/var/lib/postgresql/data"
    networks:
      - internal
    env_file:
      - .env

volumes:
  database:


networks:
  internal:
